export enum departmentsActionTypes {
  GET_DEPARTMENTS = 'GET_DEPARTMENTS',
  FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS',
  ADD_DEPARTMENT = 'ADD_DEPARTMENT',
  FETCH_NEW_DEPARTMENT = 'FETCH_NEW_DEPARTMENT',
  DELETE_DEPARTMENT = 'DELETE_DEPARTMENT',
  FETCH_DELETED_DEPARTMENT = 'FETCH_DELETED_DEPARTMENT' 
};
