export enum departmentsActionTypes {
  FETCH_START = 'FETCH_START',
  FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS_SUCCESS',
  FETCH_FAILURE = 'FETCH_DEPARTMENTS_FAILURE',
  ADD_DEPARTMENT = 'ADD_DEPARTMENT' 
};
