export enum departmentActionTypes {
  FETCH_DEPARTMENT_BY_ID = 'FETCH_DEPARTMENT_BY_ID',
  FETCH_DEPARTMENT_BY_ID_SUCCESS = 'FETCH_DEPARTMENT_BY_ID_SUCCESS',
  FETCH_DEPARTMENT_BY_ID_FAILURE = 'FETCH_DEPARTMENT_BY_ID_FAILURE'
};
