export enum departmentsActionTypes {
  GET_DEPARTMENTS = 'GET_DEPARTMENTS',
  FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS',
  GET_DEPARTMENTS_BY_NAME = 'GET_DEPARTMENTS_BY_NAME',
  FETCH_DEPARTMENTS_BY_NAME = 'FETCH_DEPARTMENTS_BY_NAME',
  ADD_DEPARTMENT = 'ADD_DEPARTMENT',
  FETCH_NEW_DEPARTMENT = 'FETCH_NEW_DEPARTMENT',
  EDIT_DEPARTMENT = 'EDIT_DEPARTMENT',
  FETCH_UPDATED_DEPARTMENT = 'FETCH_UPDATED_DEPARTMENT'
};
