export enum employeesActionTypes {
  ADD_EMPLOYEE = 'ADD_EMPLOYEE',
  FETCH_NEW_EMPLOYEE = 'FETCH_NEW_EMPLOYEE',
  EDIT_EMPLOYEE = 'EDIT_EMPLOYEE',
  FETCH_UPDATED_EMPLOYEE = 'FETCH_UPDATED_EMPLOYEE',
  DELETE_EMPLOYEE ='DELETE_EMPLOYEE',
  FETCH_DELETED_EMPLOYEE = 'FETCH_DELETED_EMPLOYEE'
};